# Generated by Django 5.2.2 on 2025-06-06 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Barraca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome da Barraca')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Barraca',
                'verbose_name_plural': 'Barracas',
            },
        ),
        migrations.CreateModel(
            name='Feira',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome da Feira')),
                ('endereco', models.TextField(verbose_name='Endereço Completo')),
                ('bairro', models.CharField(max_length=50)),
                ('cidade', models.CharField(default='Praia Grande', max_length=50)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('dias_funcionamento', models.CharField(help_text='Separe os dias por vírgula (ex: seg,qua,sex)', max_length=50)),
                ('horario_abertura', models.TimeField()),
                ('horario_fechamento', models.TimeField()),
                ('ativa', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Feira',
                'verbose_name_plural': 'Feiras',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='PresencaBarracaFeira',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('local_mapa', models.CharField(blank=True, max_length=100)),
                ('coordenadas', models.CharField(blank=True, help_text="Formato: 'latitude,longitude'", max_length=50)),
            ],
            options={
                'verbose_name': 'Presença de Barraca',
                'verbose_name_plural': 'Presenças de Barracas',
            },
        ),
    ]
