# Generated by Django 5.2.2 on 2025-06-05 21:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='barraca',
            name='feirante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='barracas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='barraca',
            name='feira',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='barracas', to='core.feira'),
        ),
        migrations.AddField(
            model_name='presencabarracafeira',
            name='barraca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.barraca'),
        ),
        migrations.AddField(
            model_name='presencabarracafeira',
            name='feira',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.feira'),
        ),
        migrations.AlterUniqueTogether(
            name='presencabarracafeira',
            unique_together={('feira', 'barraca', 'data')},
        ),
    ]
